### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by Alhadis** [Alhadis/Atom-Mocha#1]
Planned features
-----------------------
* Collapsible object trees in unified diffs (based on [`print`](https://www.npmjs.com/package/print)ed indentation)
* Make paths in stack-traces clickable (taking the user to the respective row/column in a file)
* Chai extensions for testing language grammars:

	```js
	let line = grammar.tokenizeLine("ul > li").tokens;
	expect(line).to.have.tokens({
		"ul": "meta.selector.css entity.name.tag.css",
		">": "meta.selector.css",
		"li": "meta.selector.css"
	}); // Or something to make developing grammars easier
	```
* Support for multiple `mocha.opts` files, for scenarios when specs are stored in multiple different directories
* Allow users to customise default reporter with their stylesheet:

	```less
	#mocha::atom-mocha{
		font-size: 14px;
		font-family: Hasklig;

		.error{
			color: #f00;
		}
	}
	```
